### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by RockRoller01** [RockRoller01/skinninginfo#1]
- [x] Complete default skin template
- [x] Fixing the song selection template
- [x] Add a part for converting between ratios
- [x] make the site useable
- [x] figure out why images are not showing
