### ISSUE TITLE
Remake To-Do list

### ISSUE THREAD

**Issue by RockRoller01** [RockRoller01/skinninginfo#23]
- [x] add 404
- [x] improve embeds (see compendium embeds)
- [x] add DL buttons for song selection templates
- [x] new footer
- [x] privacy thingy
- [x] header icons
- [x] new description
- [x] highlight frontmatter instead of style attributes + a dozen layouts
- [x] import centering acc guide
- [x] mobile css (and header)
